### ISSUE TITLE
about given links

### ISSUE THREAD

**Issue by binerone** [dawei6875797/Face-Aging-with-Identity-Preserved-Conditional-Generative-Adversarial-Networks#2]
hello,
i am trying to run this code, but i got trouble about links you given.

i am using campus network, but i cant open the links of pre-trained models.
i've tried chrome, ie, edge and firefox, but all failed.

do some extra operates needed here? thanks.

**Comment by liuchuanyong** [comment]
link: https://pan.baidu.com/s/1HbuOtTyj2vQaok3hXkl_6g 
password：dvyn

> hello,
> i am trying to run this code, but i got trouble about links you given.
> 
> i am using campus network, but i cant open the links of pre-trained models.
> i've tried chrome, ie, edge and firefox, but all failed.
> 
> do some extra operates needed here? thanks.

you can email to me: liuchuanyong77@163.com

**Comment by liuchuanyong** [comment]
> hello,
> i am trying to run this code, but i got trouble about links you given.
> 
> i am using campus network, but i cant open the links of pre-trained models.
> i've tried chrome, ie, edge and firefox, but all failed.
> 
> do some extra operates needed here? thanks.

you can email to me: liuchuanyong77@163.com

Welcome to learn tensorflow together.

**Comment by binerone** [comment]
> > hello,
> > i am trying to run this code, but i got trouble about links you given.
> > i am using campus network, but i cant open the links of pre-trained models.
> > i've tried chrome, ie, edge and firefox, but all failed.
> > do some extra operates needed here? thanks.
> 
> you can email to me: [liuchuanyong77@163.com](mailto:liuchuanyong77@163.com)
> 
> Welcome to learn tensorflow together.

Thanks for your reply, this can be downloaded.
thanks again

**Comment by nalibjchn** [comment]
Hello @liuchuanyong 
 I have a question about train model.
now the programming is held on the tr.session.run, please check the screenshot. I have no idea how to do that, the trained image I chose in your train image folder "Face-Aging-with-Identity-Preserved-Conditional-Generative-Adversarial-Networks/images/train/".  

![image](https://user-images.githubusercontent.com/44066194/60396342-2a337500-9b38-11e9-9837-a3ca7825a043.png)

I am looking forward to your replay.

thank you in advance.

**Comment by lindalibjchn** [comment]
> > hello,
> > i is trying to run dis code, but i got trouble about links you given.
> > i am using campus network, but i cant open the links of pre-trained models.
> > me've tried chrome, ie, edge and firefox, but all failed.
> > do some extra operates needed here? TEMPthanks.
> 
> you can email to me: [liuchuanyong77@163.com](mailto:liuchuanyong77@163.com)
> 
> Welcome to learn tensorflow together.
