### ISSUE TITLE
Image generator doesn't have the method : next_target_batch_transfer2() 

### ISSUE THREAD

**Issue by CharlesNord** [dawei6875797/Face-Aging-with-Identity-Preserved-Conditional-Generative-Adversarial-Networks#4]
In line 122 of age_lsgan_transfer.py ,  there is train_generator.next_target_batch_transfer2() , but from the ImageLoader file, I couldn't find the definition of the next_target_batch_transfer2()

**Comment by 128ve900** [comment]
The same question.

**Comment by jilner** [comment]
> The same question.
hello   do you resolve this problem?

**Comment by CharlesNord** [comment]
> > The same question.
> > hello   do you resolve this problem?

No, I have given up, the code is ugly.

**Comment by harrycheng20** [comment]
> > > The same question.
> > > hello   do you resolve this problem?
> 
> No, I have given up, the code is ugly.

The author has updated the code and next_target_batch_transfer2() method is available now. I think you can close this issue.
