### ISSUE TITLE
VGG Face Inception Score Calculation 

### ISSUE THREAD

**Issue by aruamun** [dawei6875797/Face-Aging-with-Identity-Preserved-Conditional-Generative-Adversarial-Networks#5]

**Comment by Hzzone** [comment]
@klnt19 
Hi, I'm curious about Inception Score Calculation.

When I calculated the VGG face score on generated faces, ie, aged young faces into other old faces with 4 age groups, and 1 split, I only got 4. inception score which is too low than reported in the paper.

Now I have the following question: what's the way of your generating images? generating from young faces to old ones and then calculate the score?
